language: go
go:
- 1.6.2
sudo: required
services:
- rabbitmq
install: go get -t ./...
script:
- make test
notifications:
  slack:
    secure: zFHo8P/Cs34Jvh1ydOKhZBbAmykEAy0aE4Fy4fUsfylVgS57S/MZ91owX93nvDj9o1+Ohvk1hvmv6W6UXQePIjfiqnGeckZiZQis1ZIfuNBAtSaHyXZnH5JDaATZUGavYn2gGYvaz6V0tUJM9FE0VvGfbm67f55xhNRKneVBIjQte5WqSJbdM0ha55PATlB751Q1l02C5fgVKCc4itsZqMONAcKtue+Jsx+iUGgHG8GXVHnwXZXqngr904lqrQtHYm9lP74zFF3V+GROg8bjLQP1SjArqbg/BbqLNd9sYjsHjXhDbS1sonPXpHUVumu9ubC0vSf9V/odGUxp1uvscIvwr3af2/YBffOqb6T3vbOeUUCkUcUvwUPPFUoyEJ4CHLnllO/gpFs6PyBOTZFkGTJLJWR6QahzzltHgzqk+NpW5P66TI7LCMdGwk33YuGEhuFpb5M27xevESUtbeN12aD73gaUPnuwuUxR+ogoOpjvExZM576VEhjjR3NYnt6ucEztPKvssCOiG3h7VBs036mQhwVBWBiX5ufuTkzhMdoBnbmlxhIHf+U+4M+Fb6kFqnj6SGCiiIeqj4Y8X9JHhExnhYYN8dY3H0p2nyzAPjYKA7ApWFzt3v1Wy04zPi70d6X6JR1e0JcYCv9dXQ6mf9ze8L3pvJmjS3oCVleNSKE=
